# A Docker image for running RFDiffusion using DGL on ROCm. Does not include
# RFdiffusion itself. You can mount a docker volume into the container with the
# RFdiffusion source.

FROM gcmn/dgl:rocm-complete

WORKDIR /pip
# RFdiffusion deps
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install hydra-core pyrsistent e3nn==0.3.3 decorator==5.1.0 biopython \
    && rm -rf /pip

WORKDIR /
